xgboost:
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 100

random_forest:
  n_estimators: 100
  max_depth: None
  min_samples_split: 2

validation_method: 'comb_purged_kfold'  # Can be 'kfold', 'stratified_kfold', or 'comb_purged_kfold'


